-- MySQL Script generated by MySQL Workbench
-- Thu Jul 26 16:34:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema expressFood
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `expressFood` ;

-- -----------------------------------------------------
-- Schema expressFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expressFood` DEFAULT CHARACTER SET utf8 ;
USE `expressFood` ;

-- -----------------------------------------------------
-- Table `expressFood`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`client` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`client` (
  `numero` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `raison_sociale` VARCHAR(100) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `mot_de_passe` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`numero`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`adresse` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`adresse` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_rue` VARCHAR(10) NULL DEFAULT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `complement_adresse` VARCHAR(100) NULL DEFAULT NULL,
  `code_postal` VARCHAR(10) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `client_numero` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adresse_client_numero` (`client_numero` ASC),
  CONSTRAINT `fk_adresse_client_numero`
    FOREIGN KEY (`client_numero`)
    REFERENCES `expressFood`.`client` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`statut_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`statut_commande` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`statut_commande` (
  `id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`statut_livreur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`statut_livreur` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`statut_livreur` (
  `id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`livreur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`livreur` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`livreur` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `latitude` FLOAT(10,6) NULL DEFAULT NULL,
  `longitude` FLOAT(10,6) NULL DEFAULT NULL,
  `statut_livreur_id` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livreur_statut_livreur_id` (`statut_livreur_id` ASC),
  CONSTRAINT `fk_livreur_statut_livreur_id`
    FOREIGN KEY (`statut_livreur_id`)
    REFERENCES `expressFood`.`statut_livreur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`commande` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`commande` (
  `numero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_commande` DATETIME NOT NULL,
  `date_livraison` DATETIME NULL DEFAULT NULL,
  `client_numero` MEDIUMINT(8) UNSIGNED NOT NULL,
  `adresse_id` INT UNSIGNED NOT NULL,
  `statut_commande_id` SMALLINT(3) UNSIGNED NOT NULL,
  `livreur_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_commande_client_id` (`client_numero` ASC),
  INDEX `fk_commande_adresse_id` (`adresse_id` ASC),
  INDEX `fk_commande_statut_commande_id` (`statut_commande_id` ASC),
  INDEX `fk_commande_livreur_id` (`livreur_id` ASC),
  CONSTRAINT `fk_commande_client_numero`
    FOREIGN KEY (`client_numero`)
    REFERENCES `expressFood`.`client` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_adresse_id`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `expressFood`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_statut_commande_id`
    FOREIGN KEY (`statut_commande_id`)
    REFERENCES `expressFood`.`statut_commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_livreur_id`
    FOREIGN KEY (`livreur_id`)
    REFERENCES `expressFood`.`livreur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`facture` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`facture` (
  `numero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_facture` DATE NOT NULL,
  `numero_transaction` INT UNSIGNED NOT NULL,
  `adresse_id` INT UNSIGNED NOT NULL,
  `commande_numero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_facture_adresse_id` (`adresse_id` ASC),
  INDEX `fk_facture_commande_numero` (`commande_numero` ASC),
  UNIQUE INDEX `numero_transaction_UNIQUE` (`numero_transaction` ASC),
  CONSTRAINT `fk_facture_adresse_id`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `expressFood`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_commande_numero`
    FOREIGN KEY (`commande_numero`)
    REFERENCES `expressFood`.`commande` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`categorie` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`categorie` (
  `id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`plat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`plat` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`plat` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prix_unitaire` DECIMAL(5,2) UNSIGNED NOT NULL,
  `description` TEXT(1000) NOT NULL,
  `photo` VARCHAR(255) NOT NULL,
  `categorie_id` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_plat_categorie_id` (`categorie_id` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC),
  CONSTRAINT `fk_plat_categorie_id`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `expressFood`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`jour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`jour` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`jour` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_jour` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`menu` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`menu` (
  `plat_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `jour_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `quantite` MEDIUMINT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`plat_id`, `jour_id`),
  INDEX `fk_menu_jour_id` (`jour_id` ASC),
  CONSTRAINT `fk_menu_plat_id`
    FOREIGN KEY (`plat_id`)
    REFERENCES `expressFood`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_jour_id`
    FOREIGN KEY (`jour_id`)
    REFERENCES `expressFood`.`jour` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`stock` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`stock` (
  `livreur_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `plat_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `date_stock` DATE NOT NULL,
  `quantite_initiale` SMALLINT(3) UNSIGNED NOT NULL,
  `quantite_reelle` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`livreur_id`, `plat_id`),
  INDEX `fk_stock_plat_id` (`plat_id` ASC),
  CONSTRAINT `fk_stock_livreur_id`
    FOREIGN KEY (`livreur_id`)
    REFERENCES `expressFood`.`livreur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_plat_id`
    FOREIGN KEY (`plat_id`)
    REFERENCES `expressFood`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`ligne_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expressFood`.`ligne_commande` ;

CREATE TABLE IF NOT EXISTS `expressFood`.`ligne_commande` (
  `commande_numero` INT UNSIGNED NOT NULL,
  `plat_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `quantite` SMALLINT(3) UNSIGNED NOT NULL,
  `prix_unitaire` DECIMAL(5,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`commande_numero`, `plat_id`),
  INDEX `fk_ligne_commande_plat_id` (`plat_id` ASC),
  CONSTRAINT `fk_ligne_commande_commande_numero`
    FOREIGN KEY (`commande_numero`)
    REFERENCES `expressFood`.`commande` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne_commande_plat_id`
    FOREIGN KEY (`plat_id`)
    REFERENCES `expressFood`.`plat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
